// <auto-generated />
using System;
using EstateSales.Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstateSales.Backend.Migrations
{
    [DbContext(typeof(EstateMySqlContext))]
    [Migration("20241128215457_m2-Advertisement_frissitve")]
    partial class m2Advertisement_frissitve
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Advertisement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("BaseArea")
                        .HasColumnType("double");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("int");

                    b.Property<string>("Confort")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FloorLevel")
                        .HasColumnType("int");

                    b.Property<bool>("HasElevator")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MainBuildingFloorLevel")
                        .HasColumnType("int");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhotosPath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("623fb916-4fba-4c48-8194-da46a418a2ee"),
                            BaseArea = 75.5,
                            BuiltYear = 2010,
                            Confort = "Luxus",
                            Description = "Tágas, világos lakás remek közlekedéssel.",
                            FloorLevel = 2,
                            HasElevator = true,
                            MainBuildingFloorLevel = 4,
                            Orientation = "Dél",
                            PhotosPath = "[]",
                            Price = 45000000.0,
                            RoomNumber = 3,
                            Title = "Modern lakás a belvárosban",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("4162e3aa-74cd-40c4-be8d-2e2fed210f5d"),
                            BaseArea = 120.0,
                            BuiltYear = 2005,
                            Confort = "Komfortos",
                            Description = "Csendes környék, nagy kerttel.",
                            FloorLevel = 0,
                            HasElevator = false,
                            MainBuildingFloorLevel = 1,
                            Orientation = "Nyugat",
                            PhotosPath = "[]",
                            Price = 85000000.0,
                            RoomNumber = 4,
                            Title = "Családi ház kertvárosi övezetben",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("63f5a5f8-08e6-40db-a265-47ef283edc89"),
                            BaseArea = 50.0,
                            BuiltYear = 1980,
                            Confort = "Alap",
                            Description = "Kiváló befektetési lehetőség a belvárosban.",
                            FloorLevel = 3,
                            HasElevator = false,
                            MainBuildingFloorLevel = 5,
                            Orientation = "Észak",
                            PhotosPath = "[]",
                            Price = 30000000.0,
                            RoomNumber = 2,
                            Title = "Felújítandó lakás",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("d0b2eec0-b070-463b-8620-d62429371c10"),
                            BaseArea = 200.0,
                            BuiltYear = 2022,
                            Confort = "Extra luxus",
                            Description = "Luxus szintű lakás panorámás kilátással.",
                            FloorLevel = 5,
                            HasElevator = true,
                            MainBuildingFloorLevel = 5,
                            Orientation = "Kelet-Dél",
                            PhotosPath = "[]",
                            Price = 150000000.0,
                            RoomNumber = 5,
                            Title = "Új építésű penthouse",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SenderEmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d5e3a1b-fa5f-4d5e-828e-f8fed77c666e"),
                            Content = "Szia Elek!\nÉrdekel a házad!",
                            CreatedAt = new DateTime(2024, 11, 28, 22, 54, 56, 657, DateTimeKind.Local).AddTicks(7001),
                            SenderEmailAddress = "mirmur@gmail.com",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        },
                        new
                        {
                            Id = new Guid("0e61ad7e-a5b6-4d96-9e98-d138a2fa0b45"),
                            Content = "Szia Eszter!\nÉrdekel a házad!",
                            CreatedAt = new DateTime(2024, 11, 28, 22, 54, 56, 657, DateTimeKind.Local).AddTicks(7059),
                            SenderEmailAddress = "frakk@gmail.com",
                            UserId = new Guid("00000000-0000-0000-0000-000000000000")
                        });
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fd3a5dd7-2f22-4d72-806b-01ed2bb3d71f"),
                            Email = "mekk@mek.com",
                            Name = "Mekk Elek",
                            Number = "+36/309025476",
                            Password = "mekmek"
                        },
                        new
                        {
                            Id = new Guid("23151404-ded3-4b55-bdf0-58b41137d9d7"),
                            Email = "teszt@teszt.com",
                            Name = "Teszt Eszter",
                            Number = "+36-20-735-2742",
                            Password = "teszt"
                        });
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Advertisement", b =>
                {
                    b.HasOne("EstateSales.Backend.Datas.Entities.User", "User")
                        .WithMany("Advertisements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Message", b =>
                {
                    b.HasOne("EstateSales.Backend.Datas.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.User", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
