// <auto-generated />
using System;
using EstateSales.Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstateSales.Backend.Migrations
{
    [DbContext(typeof(EstateMySqlContext))]
    partial class EstateMySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Advertisement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HasAirCondition")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasGarage")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("990f1a72-9278-4cd0-a783-8888a32e22c5"),
                            Description = "A spacious apartment in the city center with modern amenities.",
                            HasAirCondition = true,
                            HasGarage = true,
                            RoomNumber = 3,
                            Title = "Beautiful Apartment"
                        },
                        new
                        {
                            Id = new Guid("217ce06d-1a80-4209-b66d-4c31e179a6bd"),
                            Description = "A comfortable studio in a quiet neighborhood, perfect for singles.",
                            HasAirCondition = false,
                            HasGarage = false,
                            RoomNumber = 1,
                            Title = "Cozy Studio Apartment"
                        },
                        new
                        {
                            Id = new Guid("73dc4529-f3b2-4282-8d9c-c9618092a590"),
                            Description = "A luxury penthouse with stunning city views, ideal for families or executives.",
                            HasAirCondition = true,
                            HasGarage = true,
                            RoomNumber = 5,
                            Title = "Luxury Penthouse Suite"
                        },
                        new
                        {
                            Id = new Guid("f6293251-d616-4201-a46e-8190b221d460"),
                            Description = "A stylish loft with open space design and close to all amenities.",
                            HasAirCondition = true,
                            HasGarage = false,
                            RoomNumber = 2,
                            Title = "Modern Loft"
                        });
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9b3c98cc-4b07-4168-a167-8c5e84b0b717"),
                            Email = "mekk@mek.com",
                            Name = "Mekk Elek",
                            Number = "+36/309025476",
                            Password = "mekmek"
                        },
                        new
                        {
                            Id = new Guid("084b8040-fdd3-4384-9e3f-c29ef145fa48"),
                            Email = "teszt@teszt.com",
                            Name = "Teszt Eszter",
                            Number = "+36-20-735-2742",
                            Password = "teszt"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
