// <auto-generated />
using System;
using EstateSales.Backend.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EstateSales.Backend.Migrations
{
    [DbContext(typeof(EstateMySqlContext))]
    partial class EstateMySqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Advertisement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<double>("BaseArea")
                        .HasColumnType("double");

                    b.Property<int>("BuiltYear")
                        .HasColumnType("int");

                    b.Property<string>("Confort")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("FloorLevel")
                        .HasColumnType("int");

                    b.Property<bool>("HasElevator")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MainBuildingFloorLevel")
                        .HasColumnType("int");

                    b.Property<string>("Orientation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Advertisements");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef4b28b9-1a17-4c37-b647-7bf18ebd2aba"),
                            BaseArea = 75.5,
                            BuiltYear = 2010,
                            Confort = "Luxus",
                            Description = "Tágas, világos lakás remek közlekedéssel.",
                            FloorLevel = 2,
                            HasElevator = true,
                            MainBuildingFloorLevel = 4,
                            Orientation = "Dél",
                            Price = 45000000.0,
                            RoomNumber = 3,
                            Title = "Modern lakás a belvárosban"
                        },
                        new
                        {
                            Id = new Guid("39dd19f3-e486-481d-90a9-bf3e6ec9694b"),
                            BaseArea = 120.0,
                            BuiltYear = 2005,
                            Confort = "Komfortos",
                            Description = "Csendes környék, nagy kerttel.",
                            FloorLevel = 0,
                            HasElevator = false,
                            MainBuildingFloorLevel = 1,
                            Orientation = "Nyugat",
                            Price = 85000000.0,
                            RoomNumber = 4,
                            Title = "Családi ház kertvárosi övezetben"
                        },
                        new
                        {
                            Id = new Guid("6e336009-ea37-4d87-9a98-2dffef21f4b6"),
                            BaseArea = 50.0,
                            BuiltYear = 1980,
                            Confort = "Alap",
                            Description = "Kiváló befektetési lehetőség a belvárosban.",
                            FloorLevel = 3,
                            HasElevator = false,
                            MainBuildingFloorLevel = 5,
                            Orientation = "Észak",
                            Price = 30000000.0,
                            RoomNumber = 2,
                            Title = "Felújítandó lakás"
                        },
                        new
                        {
                            Id = new Guid("5738cfed-8495-413e-97f4-9c642b6a4e53"),
                            BaseArea = 200.0,
                            BuiltYear = 2022,
                            Confort = "Extra luxus",
                            Description = "Luxus szintű lakás panorámás kilátással.",
                            FloorLevel = 5,
                            HasElevator = true,
                            MainBuildingFloorLevel = 5,
                            Orientation = "Kelet-Dél",
                            Price = 150000000.0,
                            RoomNumber = 5,
                            Title = "Új építésű penthouse"
                        });
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SenderEmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c1195499-d33b-46be-a190-b0c9701c2632"),
                            Content = "Szia Elek!\nÉrdekel a házad!",
                            CreatedAt = new DateTime(2024, 12, 5, 22, 51, 37, 56, DateTimeKind.Local).AddTicks(9711),
                            SenderEmailAddress = "mirmur@gmail.com"
                        },
                        new
                        {
                            Id = new Guid("840a4d02-d98b-41b1-a5d2-85a37e1c8e3f"),
                            Content = "Szia Eszter!\nÉrdekel a házad!",
                            CreatedAt = new DateTime(2024, 12, 5, 22, 51, 37, 56, DateTimeKind.Local).AddTicks(9769),
                            SenderEmailAddress = "frakk@gmail.com"
                        });
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AdvertisementId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ImagePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdvertisementId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5fab70bd-b457-4da5-ad55-8bb41cb789f4"),
                            Email = "mekk@mek.com",
                            Name = "Mekk Elek",
                            Number = "+36/309025476",
                            Password = "mekmek"
                        },
                        new
                        {
                            Id = new Guid("0991eebc-df6a-43c7-9672-fa54b23bb001"),
                            Email = "teszt@teszt.com",
                            Name = "Teszt Eszter",
                            Number = "+36-20-735-2742",
                            Password = "teszt"
                        });
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Advertisement", b =>
                {
                    b.HasOne("EstateSales.Backend.Datas.Entities.User", "User")
                        .WithMany("Advertisements")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Message", b =>
                {
                    b.HasOne("EstateSales.Backend.Datas.Entities.User", "User")
                        .WithMany("Messages")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Photo", b =>
                {
                    b.HasOne("EstateSales.Backend.Datas.Entities.Advertisement", "Advertisement")
                        .WithMany("Photos")
                        .HasForeignKey("AdvertisementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advertisement");
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.Advertisement", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("EstateSales.Backend.Datas.Entities.User", b =>
                {
                    b.Navigation("Advertisements");

                    b.Navigation("Messages");
                });
#pragma warning restore 612, 618
        }
    }
}
